### PR TITLE
Suggestion: Migrate to Gradle

### PR DESCRIPTION
**Pull request by tamaracha**
This PR migrates the project from ant with local jar files to gradle.

- Gradle DX is way more reliable across different build environments out of the box. No manual changes to files should be necessary to build, run, test, and package.
- Dependencies are versioned maven packages instead of local jar files.
- On windows and macOS, the respective native SWT dependency is included.
- Gradle is configured to create installer packages for win and mac. It can only package for the platform it runs on, automatic build could be done via github actions CI (matrix build).
- SWT language pack is included for consistent translations.
- SWT for M1 Mac is currently missing, Eclipse should publish this to maven.
- Readme contains instructions for development setup.
- I can run the app directly from gradle or as installed package on macOS and Windows.

### CODE REVIEW

**Comment by kschroeer** [comment]
This looks very good. Thank you for your dedication!

I just have a few minor comments if you like:

- swt-linux support could still be added
- It looks like you are installing version 3 of SWT, but the current version is 4.23
- appName in the Context class could be pulled from the Constants list, so it wouldn't be necessary
- I actually don't want to use java.awt anymore, it's outdated; if you don't want to use java.lang.Runtime, JNA would be a better choice
- version=1.0.0 in gradle.properties I would set to 0.3.0, as there will be a lot of changes to the project and version 1 signals more of a stable release
- CHANGELOG.md still needs to be added

**Comment by tamaracha** [comment]
Thanks for your feedback. I strived to keep the footprint of this PR as small as possible, some of your points are actually feature requests, but valid of course.

Upgrading SWT: I tried to use the newest version, but there are incompatibilities in the code which would make the PR even larger. The files in your lib folder looked like they were a few years old, and the versioning schema of the maven packages is not aligned with these jars. So I picked a version from 2020. I would make another PR for upgrading SWT.

Adding linux support: This wasn't added before, so the same applies as for upgrading SWT. This can be a follow-up PR, maybe you want to create an issue.

Right, I replaced the app name literal with the constant. :-)

I'd leave the version out until the first release and a releasing strategy emerges. Seems that jpackage has platform/os-specific constraints for versioning schema. A general versioning strategy should be figured out separately. See the [related issue](https://github.com/beryx/badass-jlink-plugin/issues/204).

Yes, I am really not happy with the awt dependency. You were running shell commands to open folders and URLs using `exec`. Doing such things and letting this leak into app code introduces maintenance overhead for app developers, reduces stability and confidence, makes testing difficult and complicated, leads to customer issues that are difficult to analyze. Shell commands can go wrong in 1001 ways and no single app developer can anticipate them all. People tend to develop against their dev environment, mainly testing the „happy path“. For situations like opening a folder or browsing an URL you want to use a platform-agnostic abstraction in your app with a well-tested isolated implementation behind it. This implementation needs integration testing on different platforms. Although awt as a UI toolkit is outdated, it offers these abstractions and implementations, and it is not a third-party dependency. Maybe they should separate such facilities from the UI stuff, or SWT should offer them itself. I couldn't find another one and I'm not aware of JNA solving this problem of a missing abstraction. If you really want to implement such stuff yourself, it would be more useful to make a decoupled dedicated package for platform-agnostic desktop facilities, including automated integration testing.

I updated the changelog according to the [keep a changelog](https://keepachangelog.com/en/1.1.0/) guidelines. Changelogs are useful for letting others know about new features, fixed problems and breaking changes. Seems you put development-related implementation details into the changelog which can be seen from the git commit log by a seasoned developer. An average user of an email client does not know why some added mime types could matter for them. Good changelogs translate these details into consequences for the user, the dev stuff remains in git and in the project management platform.

**Comment by tamaracha** [comment]
In case of merging, maybe you want to squash to keep the main branch clean.

**Comment by kschroeer** [comment]
However, I have to tell you that java.awt.Desktop also contains system-specific functions and since it has not been further developed for a long time, there is a high probability that you will also run into problems in the future. Mocking for tests is not entirely trivial and, above all, outsourcing it to a function library, e.g. for a mobile app, would not work.

I'm not entirely happy about the SWT downgrade. Of course it doesn't have to be the latest version, but it should at least be a version 4. Maybe you have another idea?

**Comment by tamaracha** [comment]
Yes, SWT should be upgraded. But the maven artifacts with the version [3.115.0](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt.cocoa.macosx.x86_64/3.115.0) are the newest ones that build without compile errors. With newer versions in place, I get:

> .../kilamea/app/src/main/kotlin/com/github/kilamea/view/Kilamea.kt:265:18 'val' cannot be reassigned.

How is it possible that you could use a newer version without errors? My impression is that the versions in the maven artifacts are not related to the versions on the [Eclipse download page](https://download.eclipse.org/eclipse/downloads/index.html#Stable_Builds). The newest version there is 3.126.0 and has been released a month ago.

**Comment by kschroeer** [comment]
To be honest, I haven't had time to deal with the build errors via Gradle yet. This is also the reason why I quickly started the project without Maven and loaded the libraries from the official download page and added them to the application's classpath. And it builds without any problems.
But I could imagine that developments here diverge and the Maven repo is only supplied with bug fix updates. The same to JFace. Unfortunately, the libraries have to be very version compatible. I suspect that this is currently your problem.
Maybe we have to choose a hybrid solution here?

**Comment by tamaracha** [comment]
Well, I was already wondering why there is no BOM package for the SWT platform. If versions have to be aligned, this would be appropriate. I can offer you the following, will do this tonight:

1. Revert the awt thing, this can be re-evaluated later.
2. Put your jars back into the lib folder and load them with gradle.

**Comment by kschroeer** [comment]
Sounds good!

**Comment by kschroeer** [comment]
Oh, I forgot: If you would like to replace the Runtime class, that's completely fine with me. I'd just like to keep the features as "flat" as possible and not introduce any toolkit dependencies.
But you're welcome to take a look at the ProcessBuilder class if you'd like something a bit more object-oriented.
As I said - I've only put everything together quickly due to time constraints. There is still a lot of change taking place.

**Comment by tamaracha** [comment]
- [x] awt is gone. Let's tackle the Runtime topic in near future.
- [x] SWT 3.126 on Maven Central is equivalent to Eclipse version 4.32. See [this discussion](https://github.com/eclipse-platform/eclipse.platform.swt/discussions/1370).
- [x] I added the linux binaries and the aarch64 binaries for each OS being conditionally loaded. So it should also run on M1 Mac or Windows Arm, but I'll test a bit more today.

My compile error _val cannot be re-assigned_ also occured with the mac binary from the eclipse download page. It was a little api change where a method wants var args where kotlin's shortened property setter syntax didn't work anymore. Here's the diff:

```
-        sashForm.weights = intArrayOf(1, 6)
+        sashForm.setWeights(1, 6)
```

The SWT jars from the download page have [invalid signatures since 4.31](https://www.eclipse.org/forums/index.php/t/1114591/). The artifacts from Maven Central have valid signatures. I realized that you manually removed the signature from the downloaded jar. That looks combersome if you want to support multiple platforms. I'd rather go with the Maven artifacts.

**Comment by kschroeer** [comment]
That looks very good. May I give you a little suggestion: Can you add the jar task to the `build.gradle` to create an executable JAR file? Then I would merge.

**Comment by tamaracha** [comment]
OK, if you really want that, I can do it. But maybe, [you don't need it](https://stackoverflow.com/a/21743527). :-)

The application plugin already gives you these options:

- `./gradlew run` lets you start the app directly from gradle.
- `./gradlew installDist` creates a folder structure with all jars and scripts to execute the program under `app/build/install`.
- `./gradlew distZip` or `./gradlew distTar` create archives containing this folder structure under `app/build/distributions`.

If these options do not suit your needs, adding the jar task is no problem.

**Comment by kschroeer** [comment]
Yes, of course I know the options. This is completely sufficient for development. However, Gradle is never delivered in a release.
So I'm more concerned with the subsequent distribution, e.g. for test subjects.
Personally, I'm too lazy to rework the application again. Gradle can do that.
Alternatively, you can of course also customize the launch4j.xml (for Windows) or set up the JavaAppLauncher (for macOS) to generate executable files.
There are Gradle plugins for this too. I would leave the choice up to you, whichever you like better.

**Comment by tamaracha** [comment]
All right, I have added the jar config to add the main-class attribute to the manifest.

**Comment by tamaracha** [comment]
The `jpackage` task creates installable apps and packages for the OS it is currently running.

**Comment by tamaracha** [comment]
To my knowledge, only the `run` option needs gradle, the other options just need a pre-installed JRE. Of course, this is not sufficient today. The jpackage option bundles the needed runtime modules with the app.

**Comment by kschroeer** [comment]
I think the Class-Path attribute has to be included too.

**Comment by tamaracha** [comment]
OK, Class-Path attribute should be in the manifest now.

**Comment by kschroeer** [comment]
Very good, you also used the iterator. That fits. Thank you again for your support!

**Pull request merged**
